# Generated by Django 5.1.6 on 2025-02-19 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_first_name_alter_user_last_name_bag'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bagParent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.bag')),
            ],
        ),
    ]
