# Generated by Django 5.1.6 on 2025-02-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bagitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagitem',
            name='itemId',
            field=models.IntegerField(default=-1),
        ),
    ]
