# Generated by Django 5.1.6 on 2025-02-22 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_bagitem_itemid'),
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bagitem',
            name='itemId',
        ),
        migrations.AddField(
            model_name='bagitem',
            name='clothingItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clothing.clothingitem'),
        ),
    ]
