# Generated by Django 5.1.6 on 2025-02-23 23:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
