# Generated by Django 5.1.6 on 2025-02-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_bagitem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
