# Generated by Django 5.1.6 on 2025-02-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('size', models.IntegerField(choices=[(0, 'Extra Small'), (1, 'Small'), (2, 'Medium'), (3, 'Large'), (4, 'Extra Large')])),
                ('type', models.IntegerField(choices=[(0, 'Shorts'), (1, 'Pants'), (2, 'T Shirt'), (3, 'Dress'), (4, 'Shoes'), (5, 'Hat')])),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Unisex')])),
                ('brand', models.TextField(choices=[('Nike', 'Nike'), ('Jordan', 'Jordan'), ('Tommy Hilfiger', 'Tommy Hilfiger'), ('Gucci', 'Gucci')])),
            ],
        ),
    ]
