# Generated by Django 5.1.6 on 2025-02-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='image',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
